safe_require("lib/Spel2ItemCodes")

function become_lookup_table(list)
    local lookup = {}
    for _, value in ipairs(list) do
        lookup[value] = true
    end
    return lookup
end

journal = {
    chapters = { "places", "people", "bestiary", "items", "traps" },

    places = {
        { name = "Dwelling",          id = Spel2AP.locations.place.Dwelling,         index = 1  },
        { name = "Jungle",            id = Spel2AP.locations.place.Jungle,           index = 2  },
        { name = "Volcana",           id = Spel2AP.locations.place.Volcana,          index = 3  },
        { name = "Olmec's Lair",      id = Spel2AP.locations.place.Olmecs_Lair,      index = 4  },
        { name = "Tide Pool",         id = Spel2AP.locations.place.Tide_Pool,        index = 5  },
        { name = "Abzu",              id = Spel2AP.locations.place.Abzu,             index = 6  },
        { name = "Temple of Anubis",  id = Spel2AP.locations.place.Temple,           index = 7  },
        { name = "City of Gold",      id = Spel2AP.locations.place.City_of_Gold,     index = 8  },
        { name = "Duat",              id = Spel2AP.locations.place.Duat,             index = 9  },
        { name = "Ice Caves",         id = Spel2AP.locations.place.Ice_Caves,        index = 10 },
        { name = "Neo Babylon",       id = Spel2AP.locations.place.Neo_Babylon,      index = 11 },
        { name = "Tiamat's Throne",   id = Spel2AP.locations.place.Tiamats_Throne,   index = 12 },
        { name = "Sunken City",       id = Spel2AP.locations.place.Sunken_City,      index = 13 },
        { name = "Eggplant World",    id = Spel2AP.locations.place.Eggplant_World,   index = 14 },
        { name = "Hundun's Hideaway", id = Spel2AP.locations.place.HunDunsHideaway,  index = 15 },
        { name = "Cosmic Ocean",      id = Spel2AP.locations.place.Cosmic_Ocean,     index = 16 },
    },
    people = {
        { name = "Ana Spelunky",       id = Spel2AP.locations.people.Ana_Spelunky,       index = 1  }, -- Not implemented until I figure out how to do it
        { name = "Margaret Tunnel",    id = Spel2AP.locations.people.Margaret_Tunnel,    index = 2  }, -- Not implemented until I figure out how to do it
        { name = "Colin Northward",    id = Spel2AP.locations.people.Colin_Northward,    index = 3  }, -- Not implemented until I figure out how to do it
        { name = "Roffy D. Sloth",     id = Spel2AP.locations.people.Roffy_D_Sloth,      index = 4  }, -- Not implemented until I figure out how to do it
        { name = "Alto Singh",         id = Spel2AP.locations.people.Alto_Singh,         index = 5  },
        { name = "Liz Mutton",         id = Spel2AP.locations.people.Liz_Mutton,         index = 6  },
        { name = "Nekka the Eagle",    id = Spel2AP.locations.people.Nekka_the_Eagle,    index = 7  },
        { name = "LISE Project",       id = Spel2AP.locations.people.LISE_Project,       index = 8  },
        { name = "Coco Von Diamonds",  id = Spel2AP.locations.people.Coco_Von_Diamonds,  index = 9  },
        { name = "Manfred Tunnel",     id = Spel2AP.locations.people.Manfred_Tunnel,     index = 10 },
        { name = "Little Jay",         id = Spel2AP.locations.people.Little_Jay,         index = 11 },
        { name = "Tina Flan",          id = Spel2AP.locations.people.Tina_Flan,          index = 12 },
        { name = "Valerie Crump",      id = Spel2AP.locations.people.Valerie_Crump,      index = 13 },
        { name = "Au",                 id = Spel2AP.locations.people.Au,                 index = 14 },
        { name = "Demi Von Diamonds",  id = Spel2AP.locations.people.Demi_Von_Diamonds,  index = 15 },
        { name = "Pilot",              id = Spel2AP.locations.people.Pilot,              index = 16 },
        { name = "Princess Airyn",     id = Spel2AP.locations.people.Princess_Airyn,     index = 17 },
        { name = "Dirk Yamaoka",       id = Spel2AP.locations.people.Dirk_Yamaoka,       index = 18 },
        { name = "Guy Spelunky",       id = Spel2AP.locations.people.Guy_Spelunky,       index = 19 },
        { name = "Classic Guy",        id = Spel2AP.locations.people.Classic_Guy,        index = 20 },
        { name = "Terra Tunnel",       id = Spel2AP.locations.people.Terra_Tunnel,       index = 21 },
        { name = "Hired Hand",         id = Spel2AP.locations.people.Hired_Hand,         index = 22 },
        { name = "Eggplant Child",     id = Spel2AP.locations.people.Eggplant_Child,     index = 23 },
        { name = "Shopkeeper",         id = Spel2AP.locations.people.Shopkeeper,         index = 24 },
        { name = "Tun",                id = Spel2AP.locations.people.Tun,                index = 25 },
        { name = "Yang",               id = Spel2AP.locations.people.Yang,               index = 26 },
        { name = "Madame Tusk",        id = Spel2AP.locations.people.Madame_Tusk,        index = 27 },
        { name = "Tusk's Bodyguard",   id = Spel2AP.locations.people.Tusks_Bodyguard,    index = 28 },
        { name = "Waddler",            id = Spel2AP.locations.people.Waddler,            index = 29 },
        { name = "Caveman Shopkeeper", id = Spel2AP.locations.people.Caveman_Shopkeeper, index = 30 },
        { name = "Ghist Shopkeeper",   id = Spel2AP.locations.people.Ghist_Shopkeeper,   index = 31 },
        { name = "Van Horsing",        id = Spel2AP.locations.people.Van_Horsing,        index = 32 },
        { name = "Parsley",            id = Spel2AP.locations.people.Parsley,            index = 33 },
        { name = "Parsnip",            id = Spel2AP.locations.people.Parsnip,            index = 34 },
        { name = "Parmesan",           id = Spel2AP.locations.people.Parmesan,           index = 35 },
        { name = "Sparrow",            id = Spel2AP.locations.people.Sparrow,            index = 36 },
        { name = "Beg",                id = Spel2AP.locations.people.Beg,                index = 37 },
        { name = "Eggplant King",      id = Spel2AP.locations.people.Eggplant_King,      index = 38 },
    },
    bestiary = {
        { name = "Snake",              id = Spel2AP.locations.bestiary.Snake,              index = 1  },
        { name = "Spider",             id = Spel2AP.locations.bestiary.Spider,             index = 2  },
        { name = "Bat",                id = Spel2AP.locations.bestiary.Bat,                index = 3  },
        { name = "Caveman",            id = Spel2AP.locations.bestiary.Caveman,            index = 4  },
        { name = "Skeleton",           id = Spel2AP.locations.bestiary.Skeleton,           index = 5  },
        { name = "Horned Lizard",      id = Spel2AP.locations.bestiary.Horned_Lizard,      index = 6  },
        { name = "Cave Mole",          id = Spel2AP.locations.bestiary.Cave_Mole,          index = 7  },
        { name = "Quillback",          id = Spel2AP.locations.bestiary.Quillback,          index = 8  },
        { name = "Mantrap",            id = Spel2AP.locations.bestiary.Mantrap,            index = 9  },
        { name = "Tiki Man",           id = Spel2AP.locations.bestiary.Tiki_Man,           index = 10 },
        { name = "Witch Doctor",       id = Spel2AP.locations.bestiary.Witch_Doctor,       index = 11 },
        { name = "Mosquito",           id = Spel2AP.locations.bestiary.Mosquito,           index = 12 },
        { name = "Monkey",             id = Spel2AP.locations.bestiary.Monkey,             index = 13 },
        { name = "Hang Spider",        id = Spel2AP.locations.bestiary.Hang_Spider,        index = 14 },
        { name = "Giant Spider",       id = Spel2AP.locations.bestiary.Giant_Spider,       index = 15 },
        { name = "Magmar",             id = Spel2AP.locations.bestiary.Magmar,             index = 16 },
        { name = "Robot",              id = Spel2AP.locations.bestiary.Robot,              index = 17 },
        { name = "Fire Bug",           id = Spel2AP.locations.bestiary.Fire_Bug,           index = 18 },
        { name = "Imp",                id = Spel2AP.locations.bestiary.Imp,                index = 19 },
        { name = "Lavamander",         id = Spel2AP.locations.bestiary.Lavamander,         index = 20 },
        { name = "Vampire",            id = Spel2AP.locations.bestiary.Vampire,            index = 21 },
        { name = "Vlad",               id = Spel2AP.locations.bestiary.Vlad,               index = 22 },
        { name = "Olmec",              id = Spel2AP.locations.bestiary.Olmec,              index = 23 },
        { name = "Jiangshi",           id = Spel2AP.locations.bestiary.Jiangshi,           index = 24 },
        { name = "Jiangshi Assassin",  id = Spel2AP.locations.bestiary.Jiangshi_Assassin,  index = 25 },
        { name = "Flying Fish",        id = Spel2AP.locations.bestiary.Flying_Fish,        index = 26 },
        { name = "Octopy",             id = Spel2AP.locations.bestiary.Octopy,             index = 27 },
        { name = "Hermit Crab",        id = Spel2AP.locations.bestiary.Hermit_Crab,        index = 28 },
        { name = "Pangxie",            id = Spel2AP.locations.bestiary.Pangxie,            index = 29 },
        { name = "Great Humphead",     id = Spel2AP.locations.bestiary.Great_Humphead,     index = 30 },
        { name = "Kingu",              id = Spel2AP.locations.bestiary.Kingu,              index = 31 },
        { name = "Crocman",            id = Spel2AP.locations.bestiary.Crocman,            index = 32 },
        { name = "Cobra",              id = Spel2AP.locations.bestiary.Cobra,              index = 33 },
        { name = "Mummy",              id = Spel2AP.locations.bestiary.Mummy,              index = 34 },
        { name = "Sorceress",          id = Spel2AP.locations.bestiary.Sorceress,          index = 35 },
        { name = "Cat Mummy",          id = Spel2AP.locations.bestiary.Cat_Mummy,          index = 36 },
        { name = "Necromancer",        id = Spel2AP.locations.bestiary.Necromancer,        index = 37 },
        { name = "Anubis",             id = Spel2AP.locations.bestiary.Anubis,             index = 38 },
        { name = "Ammit",              id = Spel2AP.locations.bestiary.Ammit,              index = 39 },
        { name = "Apep",               id = Spel2AP.locations.bestiary.Apep,               index = 40 },
        { name = "Anubis II",          id = Spel2AP.locations.bestiary.Anubis_II,          index = 41 },
        { name = "Osiris",             id = Spel2AP.locations.bestiary.Osiris,             index = 42 },
        { name = "UFO",                id = Spel2AP.locations.bestiary.UFO,                index = 43 },
        { name = "Alien",              id = Spel2AP.locations.bestiary.Alien,              index = 44 },
        { name = "Yeti",               id = Spel2AP.locations.bestiary.Yeti,               index = 45 },
        { name = "Yeti King",          id = Spel2AP.locations.bestiary.Yeti_King,          index = 46 },
        { name = "Yeti Queen",         id = Spel2AP.locations.bestiary.Yeti_Queen,         index = 47 },
        { name = "Lamahu",             id = Spel2AP.locations.bestiary.Lamahu,             index = 48 },
        { name = "Proto Shopkeeper",   id = Spel2AP.locations.bestiary.Proto_Shopkeeper,   index = 49 },
        { name = "Olmite",             id = Spel2AP.locations.bestiary.Olmite,             index = 50 },
        { name = "Lamassu",            id = Spel2AP.locations.bestiary.Lamassu,            index = 51 },
        { name = "Tiamat",             id = Spel2AP.locations.bestiary.Tiamat,             index = 52 },
        { name = "Tadpole",            id = Spel2AP.locations.bestiary.Tadpole,            index = 53 },
        { name = "Frog",               id = Spel2AP.locations.bestiary.Frog,               index = 54 },
        { name = "Fire Frog",          id = Spel2AP.locations.bestiary.Fire_Frog,          index = 55 },
        { name = "Goliath Frog",       id = Spel2AP.locations.bestiary.Goliath_Frog,       index = 56 },
        { name = "Grub",               id = Spel2AP.locations.bestiary.Grub,               index = 57 },
        { name = "Giant Fly",          id = Spel2AP.locations.bestiary.Giant_Fly,          index = 58 },
        { name = "Hundun",             id = Spel2AP.locations.bestiary.Hundun,             index = 59 },
        { name = "Eggplant Minister",  id = Spel2AP.locations.bestiary.Eggplant_Minister,  index = 60 },
        { name = "Eggplup",            id = Spel2AP.locations.bestiary.Eggplup,            index = 61 },
        { name = "Celestial Jelly",    id = Spel2AP.locations.bestiary.Celestial_Jelly,    index = 62 },
        { name = "Scorpion",           id = Spel2AP.locations.bestiary.Scorpion,           index = 63 },
        { name = "Bee",                id = Spel2AP.locations.bestiary.Bee,                index = 64 },
        { name = "Queen Bee",          id = Spel2AP.locations.bestiary.Queen_Bee,          index = 65 },
        { name = "Scarab",             id = Spel2AP.locations.bestiary.Scarab,             index = 66 },
        { name = "Golden Monkey",      id = Spel2AP.locations.bestiary.Golden_Monkey,      index = 67 },
        { name = "Leprechaun",         id = Spel2AP.locations.bestiary.Leprechaun,         index = 68 },
        { name = "Monty",              id = Spel2AP.locations.bestiary.Monty,              index = 69 },
        { name = "Percy",              id = Spel2AP.locations.bestiary.Percy,              index = 70 },
        { name = "Poochi",             id = Spel2AP.locations.bestiary.Poochi,             index = 71 },
        { name = "Ghist",              id = Spel2AP.locations.bestiary.Ghist,              index = 72 },
        { name = "Ghost",              id = Spel2AP.locations.bestiary.Ghost,              index = 73 },
        { name = "Cave Turkey",        id = Spel2AP.locations.bestiary.Cave_Turkey,        index = 74 },
        { name = "Rock Dog",           id = Spel2AP.locations.bestiary.Rock_Dog,           index = 75 },
        { name = "Axolotl",            id = Spel2AP.locations.bestiary.Axolotl,            index = 76 },
        { name = "Qilin",              id = Spel2AP.locations.bestiary.Qilin,              index = 77 },
        { name = "Mech Rider",         id = Spel2AP.locations.bestiary.Mech_Rider,         index = 78 },
    },
    items = {
        { name = "Rope Pile",         id = Spel2AP.locations.item.Rope_Pile,          index = 1  },
        { name = "Bomb Bag",          id = Spel2AP.locations.item.Bomb_Bag,           index = 2  },
        { name = "Bomb Box",          id = Spel2AP.locations.item.Bomb_Box,           index = 3  },
        { name = "Paste",             id = Spel2AP.locations.item.Paste,              index = 4  },
        { name = "Spectacles",        id = Spel2AP.locations.item.Spectacles,         index = 5  },
        { name = "Climbing Gloves",   id = Spel2AP.locations.item.Climbing_Gloves,    index = 6  },
        { name = "Pitcher's Mitt",    id = Spel2AP.locations.item.Pitchers_Mitt,      index = 7  },
        { name = "Spring Shoes",      id = Spel2AP.locations.item.Spring_Shoes,       index = 8  },
        { name = "Spike Shoes",       id = Spel2AP.locations.item.Spike_Shoes,        index = 9  },
        { name = "Compass",           id = Spel2AP.locations.item.Compass,            index = 10 },
        { name = "Alien Compass",     id = Spel2AP.locations.item.Alien_Compass,      index = 11 },
        { name = "Parachute",         id = Spel2AP.locations.item.Parachute,          index = 12 },
        { name = "Udjat Eye",         id = Spel2AP.locations.item.Udjat_Eye,           index = 13 },
        { name = "Kapala",            id = Spel2AP.locations.item.Kapala,             index = 14 },
        { name = "Hedjet",            id = Spel2AP.locations.item.Hedjet,              index = 15 },
        { name = "Crown",             id = Spel2AP.locations.item.Crown,               index = 16 },
        { name = "Eggplant Crown",    id = Spel2AP.locations.item.Eggplant_Crown,      index = 17 },
        { name = "True Crown",        id = Spel2AP.locations.item.True_Crown,          index = 18 },
        { name = "Ankh",              id = Spel2AP.locations.item.Ankh,                index = 19 },
        { name = "Tablet of Destiny", id = Spel2AP.locations.item.Tablet_of_Destiny,   index = 20 },
        { name = "Skeleton Key",      id = Spel2AP.locations.item.Skeleton_Key,        index = 21 },
        { name = "Royal Jelly",       id = Spel2AP.locations.item.Royal_Jelly,         index = 22 },
        { name = "Cape",              id = Spel2AP.locations.item.Cape,                index = 23 },
        { name = "Vlad's Cape",       id = Spel2AP.locations.item.Vlads_Cape,          index = 24 },
        { name = "Jetpack",           id = Spel2AP.locations.item.Jetpack,             index = 25 },
        { name = "Telepack",          id = Spel2AP.locations.item.Telepack,            index = 26 },
        { name = "Hoverpack",         id = Spel2AP.locations.item.Hoverpack,           index = 27 },
        { name = "Powerpack",         id = Spel2AP.locations.item.Powerpack,           index = 28 },
        { name = "Webgun",            id = Spel2AP.locations.item.Webgun,              index = 29 },
        { name = "Shotgun",           id = Spel2AP.locations.item.Shotgun,             index = 30 },
        { name = "Freeze Ray",        id = Spel2AP.locations.item.Freeze_Ray,          index = 31 },
        { name = "Clone Gun",         id = Spel2AP.locations.item.Clone_Gun,           index = 32 },
        { name = "Crossbow",          id = Spel2AP.locations.item.Crossbow,            index = 33 },
        { name = "Camera",            id = Spel2AP.locations.item.Camera,              index = 34 },
        { name = "Teleporter",        id = Spel2AP.locations.item.Teleporter,          index = 35 },
        { name = "Mattock",           id = Spel2AP.locations.item.Mattock,             index = 36 },
        { name = "Boomerang",         id = Spel2AP.locations.item.Boomerang,           index = 37 },
        { name = "Machete",           id = Spel2AP.locations.item.Machete,             index = 38 },
        { name = "Excalibur",         id = Spel2AP.locations.item.Excalibur,           index = 39 },
        { name = "Broken Sword",      id = Spel2AP.locations.item.Broken_Sword,        index = 40 },
        { name = "Plasma Cannon",     id = Spel2AP.locations.item.Plasma_Cannon,       index = 41 },
        { name = "Scepter",           id = Spel2AP.locations.item.Scepter,             index = 42 },
        { name = "Hou Yi's Bow",      id = Spel2AP.locations.item.Hou_Yis_Bow,         index = 43 },
        { name = "Arrow of Light",    id = Spel2AP.locations.item.Arrow_of_Light,      index = 44 },
        { name = "Wooden Shield",     id = Spel2AP.locations.item.Wooden_Shield,       index = 45 },
        { name = "Metal Shield",      id = Spel2AP.locations.item.Metal_Shield,        index = 46 },
        { name = "Idol",              id = Spel2AP.locations.item.Idol,                index = 47 },
        { name = "The Tusk Idol",     id = Spel2AP.locations.item.The_Tusk_Idol,       index = 48 },
        { name = "Curse Pot",         id = Spel2AP.locations.item.Curse_Pot,           index = 49 },
        { name = "Ushabti",           id = Spel2AP.locations.item.Ushabti,             index = 50 },
        { name = "Eggplant",          id = Spel2AP.locations.item.Eggplant,            index = 51 },
        { name = "Cooked Turkey",     id = Spel2AP.locations.item.Cooked_Turkey,       index = 52 },
        { name = "Elixir",            id = Spel2AP.locations.item.Elixir,              index = 53 },
        { name = "Four-Leaf Clover",  id = Spel2AP.locations.item.Four_Leaf_Clover,    index = 54 },
    },
    traps = {
        { name = "Spikes",            id = Spel2AP.locations.trap.Spikes,            index = 1  },
        { name = "Arrow Trap",        id = Spel2AP.locations.trap.Arrow_Trap,        index = 2  },
        { name = "Totem Trap",        id = Spel2AP.locations.trap.Totem_Trap,        index = 3  },
        { name = "Log Trap",          id = Spel2AP.locations.trap.Log_Trap,          index = 4  },
        { name = "Spear Trap",        id = Spel2AP.locations.trap.Spear_Trap,        index = 5  },
        { name = "Thorny Vine",       id = Spel2AP.locations.trap.Thorny_Vine,       index = 6  },
        { name = "Bear Trap",         id = Spel2AP.locations.trap.Bear_Trap,         index = 7  },
        { name = "Powder Box",        id = Spel2AP.locations.trap.Powder_Box,        index = 8  },
        { name = "Falling Platform",  id = Spel2AP.locations.trap.Falling_Platform,  index = 9  },
        { name = "Spikeball",         id = Spel2AP.locations.trap.Spikeball,         index = 10 },
        { name = "Lion Trap",         id = Spel2AP.locations.trap.Lion_Trap,         index = 11 },
        { name = "Giant Clam",        id = Spel2AP.locations.trap.Giant_Clam,        index = 12 },
        { name = "Sliding Wall",      id = Spel2AP.locations.trap.Sliding_Wall,      index = 13 },
        { name = "Crush Trap",        id = Spel2AP.locations.trap.Crush_Trap,        index = 14 },
        { name = "Giant Crush Trap",  id = Spel2AP.locations.trap.Giant_Crush_Trap,  index = 15 },
        { name = "Boulder",           id = Spel2AP.locations.trap.Boulder,           index = 16 },
        { name = "Spring Trap",       id = Spel2AP.locations.trap.Spring_Trap,       index = 17 },
        { name = "Landmine",          id = Spel2AP.locations.trap.Landmine,          index = 18 },
        { name = "Laser Trap",        id = Spel2AP.locations.trap.Laser_Trap,        index = 19 },
        { name = "Spark Trap",        id = Spel2AP.locations.trap.Spark_Trap,        index = 20 },
        { name = "Frog Trap",         id = Spel2AP.locations.trap.Frog_Trap,         index = 21 },
        { name = "Sticky Trap",       id = Spel2AP.locations.trap.Sticky_Trap,       index = 22 },
        { name = "Bone Drop",         id = Spel2AP.locations.trap.Bone_Drop,         index = 23 },
        { name = "Egg Sac",           id = Spel2AP.locations.trap.Egg_Sac,           index = 24 },
    }
}

journal_lookup = {}
for _, chapter in ipairs(journal.chapters) do
    for index, entry in ipairs(journal[chapter]) do
        journal_lookup[entry.id] = { chapter = chapter, index = index }
    end
end

character_data =
{
    [Spel2AP.characters.Ana_Spelunky] =
    {
        index = 1,
        ent = ENT_TYPE.CHAR_ANA_SPELUNKY,
        location = Spel2AP.locations.people.Ana_Spelunky
    },
    [Spel2AP.characters.Margaret_Tunnel] =
    {
        index = 2,
        ent = ENT_TYPE.CHAR_MARGARET_TUNNEL,
        location = Spel2AP.locations.people.Margaret_Tunnel
    },
    [Spel2AP.characters.Colin_Northward] =
    {
        index = 3,
        ent = ENT_TYPE.CHAR_COLIN_NORTHWARD,
        location = Spel2AP.locations.people.Colin_Northward
    },
    [Spel2AP.characters.Roffy_D_Sloth] =
    {
        index = 4,
        ent = ENT_TYPE.CHAR_ROFFY_D_SLOTH,
        location = Spel2AP.locations.people.Roffy_D_Sloth
    },
    [Spel2AP.characters.Alto_Singh] =
    {
        index = 5,
        ent = ENT_TYPE.CHAR_BANDA,
        location = Spel2AP.locations.people.Alto_Singh
    },
    [Spel2AP.characters.Liz_Mutton] =
    {
        index = 6,
        ent = ENT_TYPE.CHAR_GREEN_GIRL,
        location = Spel2AP.locations.people.Liz_Mutton
    },
    [Spel2AP.characters.Nekka_the_Eagle] =
    {
        index = 7,
        ent = ENT_TYPE.CHAR_AMAZON,
        location = Spel2AP.locations.people.Nekka_the_Eagle
    },
    [Spel2AP.characters.LISE_Project] =
    {
        index = 8,
        ent = ENT_TYPE.CHAR_LISE_SYSTEM,
        location = Spel2AP.locations.people.LISE_Project
    },
    [Spel2AP.characters.Coco_Von_Diamonds] =
    {
        index = 9,
        ent = ENT_TYPE.CHAR_COCO_VON_DIAMONDS,
        location = Spel2AP.locations.people.Coco_Von_Diamonds
    },
    [Spel2AP.characters.Manfred_Tunnel] =
    {
        index = 10,
        ent = ENT_TYPE.CHAR_MANFRED_TUNNEL,
        location = Spel2AP.locations.people.Manfred_Tunnel
    },
    [Spel2AP.characters.Little_Jay] =
    {
        index = 11,
        ent = ENT_TYPE.CHAR_OTAKU,
        location = Spel2AP.locations.people.Little_Jay
    },
    [Spel2AP.characters.Tina_Flan] =
    {
        index = 12,
        ent = ENT_TYPE.CHAR_TINA_FLAN,
        location = Spel2AP.locations.people.Tina_Flan
    },
    [Spel2AP.characters.Valerie_Crump] =
    {
        index = 13,
        ent = ENT_TYPE.CHAR_VALERIE_CRUMP,
        location = Spel2AP.locations.people.Valerie_Crump
    },
    [Spel2AP.characters.Au] =
    {
        index = 14,
        ent = ENT_TYPE.CHAR_AU,
        location = Spel2AP.locations.people.Au
    },
    [Spel2AP.characters.Demi_Von_Diamonds] =
    {
        index = 15,
        ent = ENT_TYPE.CHAR_DEMI_VON_DIAMONDS,
        location = Spel2AP.locations.people.Demi_Von_Diamonds
    },
    [Spel2AP.characters.Pilot] =
    {
        index = 16,
        ent = ENT_TYPE.CHAR_PILOT,
        location = Spel2AP.locations.people.Pilot
    },
    [Spel2AP.characters.Princess_Airyn] =
    {
        index = 17,
        ent = ENT_TYPE.CHAR_PRINCESS_AIRYN,
        location = Spel2AP.locations.people.Princess_Airyn
    },
    [Spel2AP.characters.Dirk_Yamaoka] =
    {
        index = 18,
        ent = ENT_TYPE.CHAR_DIRK_YAMAOKA,
        location = Spel2AP.locations.people.Dirk_Yamaoka
    },
    [Spel2AP.characters.Guy_Spelunky] =
    {
        index = 19,
        ent = ENT_TYPE.CHAR_GUY_SPELUNKY,
        location = Spel2AP.locations.people.Guy_Spelunky
    },
    [Spel2AP.characters.Classic_Guy] =
    {
        index = 20,
        ent = ENT_TYPE.CHAR_CLASSIC_GUY,
        location = Spel2AP.locations.people.Classic_Guy
    },
}

theme_to_world_unlock_id = {
    [THEME.JUNGLE]       = Spel2AP.world_unlocks.Jungle,
    [THEME.VOLCANA]      = Spel2AP.world_unlocks.Volcana,
    [THEME.OLMEC]        = Spel2AP.world_unlocks.Olmecs_Lair,
    [THEME.TIDE_POOL]    = Spel2AP.world_unlocks.Tide_Pool,
    [THEME.TEMPLE]       = Spel2AP.world_unlocks.Temple,
    [THEME.ICE_CAVES]    = Spel2AP.world_unlocks.Ice_Caves,
    [THEME.NEO_BABYLON]  = Spel2AP.world_unlocks.Neo_Babylon,
    [THEME.SUNKEN_CITY]  = Spel2AP.world_unlocks.Sunken_City,
    [THEME.COSMIC_OCEAN] = Spel2AP.world_unlocks.Cosmic_Ocean,
}

item_ids = {
    [Spel2AP.filler_items.Rope_Pile] = {
        type = Spel2AP.filler_items,
        name = "Rope Pile",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.filler_items.Bomb_Bag] = {
        type = Spel2AP.filler_items,
        name = "Bomb Bag",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 1,
    },
    [Spel2AP.filler_items.Bomb_Box] = {
        type = Spel2AP.filler_items,
        name = "Bomb Box",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 2,
    },
    [Spel2AP.filler_items.Cooked_Turkey] = {
        type = Spel2AP.filler_items,
        name = "Cooked Turkey",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 5,
    },
    [Spel2AP.filler_items.Royal_Jelly] = {
        type = Spel2AP.filler_items,
        name = "Royal Jelly",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 6,
    },
    [Spel2AP.filler_items.Gold_Bar] = {
        type = Spel2AP.filler_items,
        name = "Gold Bar",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 8,
        TileX = 12,
    },
    [Spel2AP.filler_items.Emerald_Gem] = {
        type = Spel2AP.filler_items,
        name = "Emerald",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 0,
        TileX = 3,
    },
    [Spel2AP.filler_items.Sapphire_Gem] = {
        type = Spel2AP.filler_items,
        name = "Sapphire",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 0,
        TileX = 4,
    },
    [Spel2AP.filler_items.Ruby_Gem] = {
        type = Spel2AP.filler_items,
        name = "Ruby",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 0,
        TileX = 5,
    },
    [Spel2AP.filler_items.Diamond_Gem] = {
        type = Spel2AP.filler_items,
        name = "Diamond",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 0,
        TileX = 6,
    },
    [Spel2AP.characters.Ana_Spelunky] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_ANA_SPELUNKY),
        display = TEXTURE.DATA_TEXTURES_CHAR_YELLOW_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Margaret_Tunnel] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_MARGARET_TUNNEL),
        display = TEXTURE.DATA_TEXTURES_CHAR_MAGENTA_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Colin_Northward] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_COLIN_NORTHWARD),
        display = TEXTURE.DATA_TEXTURES_CHAR_CYAN_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Roffy_D_Sloth] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_ROFFY_D_SLOTH),
        display = TEXTURE.DATA_TEXTURES_CHAR_BLACK_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Alto_Singh] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_BANDA),
        display = TEXTURE.DATA_TEXTURES_CHAR_CINNABAR_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Liz_Mutton] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_GREEN_GIRL),
        display = TEXTURE.DATA_TEXTURES_CHAR_GREEN_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Nekka_the_Eagle] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_AMAZON),
        display = TEXTURE.DATA_TEXTURES_CHAR_OLIVE_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.LISE_Project] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_LISE_SYSTEM),
        display = TEXTURE.DATA_TEXTURES_CHAR_WHITE_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Coco_Von_Diamonds] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_COCO_VON_DIAMONDS),
        display = TEXTURE.DATA_TEXTURES_CHAR_CERULEAN_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Manfred_Tunnel] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_MANFRED_TUNNEL),
        display = TEXTURE.DATA_TEXTURES_CHAR_BLUE_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Little_Jay] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_OTAKU),
        display = TEXTURE.DATA_TEXTURES_CHAR_LIME_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Tina_Flan] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_TINA_FLAN),
        display = TEXTURE.DATA_TEXTURES_CHAR_LEMON_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Valerie_Crump] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_VALERIE_CRUMP),
        display = TEXTURE.DATA_TEXTURES_CHAR_IRIS_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Au] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_AU),
        display = TEXTURE.DATA_TEXTURES_CHAR_GOLD_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Demi_Von_Diamonds] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_DEMI_VON_DIAMONDS),
        display = TEXTURE.DATA_TEXTURES_CHAR_RED_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Pilot] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_PILOT),
        display = TEXTURE.DATA_TEXTURES_CHAR_PINK_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Princess_Airyn] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_PRINCESS_AIRYN),
        display = TEXTURE.DATA_TEXTURES_CHAR_VIOLET_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Dirk_Yamaoka] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_DIRK_YAMAOKA),
        display = TEXTURE.DATA_TEXTURES_CHAR_GRAY_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Guy_Spelunky] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_GUY_SPELUNKY),
        display = TEXTURE.DATA_TEXTURES_CHAR_KHAKI_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.characters.Classic_Guy] = {
        type = Spel2AP.characters,
        name = get_character_name(ENT_TYPE.CHAR_CLASSIC_GUY),
        display = TEXTURE.DATA_TEXTURES_CHAR_ORANGE_0,
        TileY = 0,
        TileX = 0,
    },
    [Spel2AP.locked_items.Alien_Compass] = {
        type = Spel2AP.locked_items,
        name = "Alien Compass Unlocked",
        lock_name = "Alien Compass",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 8,
    },
    [Spel2AP.locked_items.Ankh] = {
        type = Spel2AP.locked_items,
        name = "Ankh Unlocked",
        lock_name = "Ankh",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 5,
    },
    [Spel2AP.locked_items.Arrow_of_Light] = {
        type = Spel2AP.locked_items,
        name = "Arrow of Light Unlocked",
        lock_name = "Arrow of Light",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 5,
        TileX = 1,
    },
    [Spel2AP.locked_items.Camera] = {
        type = Spel2AP.locked_items,
        name = "Camera Unlocked",
        lock_name = "Camera",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 4,
    },
    [Spel2AP.locked_items.Cape] = {
        type = Spel2AP.locked_items,
        name = "Cape Unlocked",
        lock_name = "Cape",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 7,
    },
    [Spel2AP.locked_items.Climbing_Gloves] = {
        type = Spel2AP.locked_items,
        name = "Climbing Gloves Unlocked",
        lock_name = "Climbing Gloves",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 5,
    },
    [Spel2AP.locked_items.Clone_Gun] = {
        type = Spel2AP.locked_items,
        name = "Clone Gun Unlocked",
        lock_name = "Clone Gun",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 7,
    },
    [Spel2AP.locked_items.Compass] = {
        type = Spel2AP.locked_items,
        name = "Compass Unlocked",
        lock_name = "Compass",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 9,
    },
    [Spel2AP.locked_items.Crown] = {
        type = Spel2AP.locked_items,
        name = "Crown Unlocked",
        lock_name = "Crown",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 4,
    },
    [Spel2AP.locked_items.Eggplant] = {
        type = Spel2AP.locked_items,
        name = "Eggplant Unlocked",
        lock_name = "Eggplant",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 4,
    },
    [Spel2AP.locked_items.Eggplant_Crown] = {
        type = Spel2AP.locked_items,
        name = "Eggplant Crown Unlocked",
        lock_name = "Eggplant Crown",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 5,
        TileX = 3,
    },
    [Spel2AP.locked_items.Elixir] = {
        type = Spel2AP.locked_items,
        name = "Elixir Unlocked",
        lock_name = "Elixir",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 6,
    },
    [Spel2AP.locked_items.Excalibur] = {
        type = Spel2AP.locked_items,
        name = "Excalibur Unlocked",
        lock_name = "Excalibur",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 2,
        TileY = 10
    },
    [Spel2AP.locked_items.Four_Leaf_Clover] = {
        type = Spel2AP.locked_items,
        name = "Four-Leaf Clover Unlocked",
        lock_name = "Four-Leaf Clover",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 2,
    },
    [Spel2AP.locked_items.Freeze_Ray] = {
        type = Spel2AP.locked_items,
        name = "Freeze Ray Unlocked",
        lock_name = "Freeze Ray",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 2,
    },
    [Spel2AP.locked_items.Hedjet] = {
        type = Spel2AP.locked_items,
        name = "Hedjet Unlocked",
        lock_name = "Hedjet",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 3,
    },
    [Spel2AP.locked_items.Hoverpack] = {
        type = Spel2AP.locked_items,
        name = "Hoverpack Unlocked",
        lock_name = "Hoverpack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 6,
    },
    [Spel2AP.locked_items.Hou_Yis_Bow] = {
        type = Spel2AP.locked_items,
        name = "Hou Yi's Bow Unlocked",
        lock_name = "Hou Yi's Bow",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 5,
        TileX = 0,
    },
    [Spel2AP.locked_items.Jetpack] = {
        type = Spel2AP.locked_items,
        name = "Jetpack Unlocked",
        lock_name = "Jetpack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 8,
    },
    [Spel2AP.locked_items.Kapala] = {
        type = Spel2AP.locked_items,
        name = "Kapala Unlocked",
        lock_name = "Kapala",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 2,
    },
    [Spel2AP.locked_items.Machete] = {
        type = Spel2AP.locked_items,
        name = "Machete Unlocked",
        lock_name = "Machete",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 8,
    },
    [Spel2AP.locked_items.Mattock] = {
        type = Spel2AP.locked_items,
        name = "Mattock Unlocked",
        lock_name = "Mattock",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 6,
    },
    [Spel2AP.locked_items.Paste] = {
        type = Spel2AP.locked_items,
        name = "Paste Unlocked",
        lock_name = "Paste",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 3,
    },
    [Spel2AP.locked_items.Pitchers_Mitt] = {
        type = Spel2AP.locked_items,
        name = "Pitcher's Mitt Unlocked",
        lock_name = "Pitcher's Mitt",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 6,
    },
    [Spel2AP.locked_items.Plasma_Cannon] = {
        type = Spel2AP.locked_items,
        name = "Plasma Cannon Unlocked",
        lock_name = "Plasma Cannon",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 0,
    },
    [Spel2AP.locked_items.Powerpack] = {
        type = Spel2AP.locked_items,
        name = "Powerpack Unlocked",
        lock_name = "Powerpack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 4,
    },
    [Spel2AP.locked_items.Scepter] = {
        type = Spel2AP.locked_items,
        name = "Scepter Unlocked",
        lock_name = "Scepter",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 1,
    },
    [Spel2AP.locked_items.Shield] = {
        type = Spel2AP.locked_items,
        name = "Shield Unlocked",
        lock_name = "Shield",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 1,
    },
    [Spel2AP.locked_items.Skeleton_Key] = {
        type = Spel2AP.locked_items,
        name = "Skeleton Key Unlocked",
        lock_name = "Skeleton Key",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 8,
    },
    [Spel2AP.locked_items.Spectacles] = {
        type = Spel2AP.locked_items,
        name = "Spectacles Unlocked",
        lock_name = "Spectacles",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 4,
    },
    [Spel2AP.locked_items.Spike_Shoes] = {
        type = Spel2AP.locked_items,
        name = "Spike Shoes Unlocked",
        lock_name = "Spike Shoes",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 8,
    },
    [Spel2AP.locked_items.Spring_Shoes] = {
        type = Spel2AP.locked_items,
        name = "Spring Shoes Unlocked",
        lock_name = "Spring Shoes",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 7,
    },
    [Spel2AP.locked_items.Tablet_of_Destiny] = {
        type = Spel2AP.locked_items,
        name = "Tablet of Destiny Unlocked",
        lock_name = "Tablet of Destiny",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 9,
    },
    [Spel2AP.locked_items.Telepack] = {
        type = Spel2AP.locked_items,
        name = "Telepack Unlocked",
        lock_name = "Telepack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 9,
    },
    [Spel2AP.locked_items.Teleporter] = {
        type = Spel2AP.locked_items,
        name = "Teleporter Unlocked",
        lock_name = "Teleporter",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 5,
    },
    [Spel2AP.locked_items.True_Crown] = {
        type = Spel2AP.locked_items,
        name = "True Crown Unlocked",
        lock_name = "True Crown",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 3,
    },
    [Spel2AP.locked_items.Udjat_Eye] = {
        type = Spel2AP.locked_items,
        name = "Udjat Eye Unlocked",
        lock_name = "Udjat Eye",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 1,
    },
    [Spel2AP.locked_items.Ushabti] = {
        type = Spel2AP.locked_items,
        name = "Ushabti Unlocked",
        lock_name = "Ushabti",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 3,
    },
    [Spel2AP.locked_items.Vlads_Cape] = {
        type = Spel2AP.locked_items,
        name = "Vlad's Cape Unlocked",
        lock_name = "Vlad's Cape",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 5,
    },
    [Spel2AP.locked_items.Webgun] = {
        type = Spel2AP.locked_items,
        name = "Webgun Unlocked",
        lock_name = "Webgun",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 0,
    },
    [Spel2AP.upgrades.Ankh] = {
        type = Spel2AP.upgrades,
        name = "Starter Ankh",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 5,
    },
    [Spel2AP.upgrades.Camera] = {
        type = Spel2AP.upgrades,
        name = "Starter Camera",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 4,
    },
    [Spel2AP.upgrades.Cape] = {
        type = Spel2AP.upgrades,
        name = "Starter Cape",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 7,
    },
    [Spel2AP.upgrades.Climbing_Gloves] = {
        type = Spel2AP.upgrades,
        name = "Starter Climbing Gloves",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 5,
    },
    [Spel2AP.upgrades.Clone_Gun] = {
        type = Spel2AP.upgrades,
        name = "Starter Clone Gun",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 7,
    },
    [Spel2AP.upgrades.Compass] = {
        type = Spel2AP.upgrades,
        name = "Starter Compass",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 9,
    },
    [Spel2AP.upgrades.Eggplant] = {
        type = Spel2AP.upgrades,
        name = "Starter Eggplant",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 4,
    },
    [Spel2AP.upgrades.Eggplant_Crown] = {
        type = Spel2AP.upgrades,
        name = "Starter Eggplant Crown",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 5,
        TileX = 3,
    },
    [Spel2AP.upgrades.Elixir] = {
        type = Spel2AP.upgrades,
        name = "Starter Elixir",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 6,
    },
    [Spel2AP.upgrades.Four_Leaf_Clover] = {
        type = Spel2AP.upgrades,
        name = "Permanent Four-Leaf Clover",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 2,
    },
    [Spel2AP.upgrades.Freeze_Ray] = {
        type = Spel2AP.upgrades,
        name = "Starter Freeze Ray",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 2,
    },
    [Spel2AP.upgrades.Hoverpack] = {
        type = Spel2AP.upgrades,
        name = "Starter Hoverpack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 6,
    },
    [Spel2AP.upgrades.Jetpack] = {
        type = Spel2AP.upgrades,
        name = "Starter Jetpack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 8,
    },
    [Spel2AP.upgrades.Kapala] = {
        type = Spel2AP.upgrades,
        name = "Starter Kapala",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 2,
    },
    [Spel2AP.upgrades.Machete] = {
        type = Spel2AP.upgrades,
        name = "Starter Machete",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 8,
    },
    [Spel2AP.upgrades.Mattock] = {
        type = Spel2AP.upgrades,
        name = "Starter Mattock",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 6,
    },
    [Spel2AP.upgrades.Paste] = {
        type = Spel2AP.upgrades,
        name = "Starter Paste",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 3,
    },
    [Spel2AP.upgrades.Pitchers_Mitt] = {
        type = Spel2AP.upgrades,
        name = "Starter Pitcher's Mitt",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 6,
    },
    [Spel2AP.upgrades.Plasma_Cannon] = {
        type = Spel2AP.upgrades,
        name = "Starter Plasma Cannon",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 0,
    },
    [Spel2AP.upgrades.Powerpack] = {
        type = Spel2AP.upgrades,
        name = "Starter Powerpack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 4,
    },
    [Spel2AP.upgrades.Shield] = {
        type = Spel2AP.upgrades,
        name = "Starter Shield",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 1,
    },
    [Spel2AP.upgrades.Skeleton_Key] = {
        type = Spel2AP.upgrades,
        name = "Starter Skeleton Key",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 8,
    },
    [Spel2AP.upgrades.Spectacles] = {
        type = Spel2AP.upgrades,
        name = "Starter Spectacles",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 4,
    },
    [Spel2AP.upgrades.Spike_Shoes] = {
        type = Spel2AP.upgrades,
        name = "Starter Spike Shoes",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 8,
    },
    [Spel2AP.upgrades.Spring_Shoes] = {
        type = Spel2AP.upgrades,
        name = "Starter Spring Shoes",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 7,
    },
    [Spel2AP.upgrades.Telepack] = {
        type = Spel2AP.upgrades,
        name = "Starter Telepack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 9,
    },
    [Spel2AP.upgrades.Teleporter] = {
        type = Spel2AP.upgrades,
        name = "Starter Teleporter",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 5,
    },
    [Spel2AP.upgrades.True_Crown] = {
        type = Spel2AP.upgrades,
        name = "Starter True Crown",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 3,
    },
    [Spel2AP.upgrades.Vlads_Cape] = {
        type = Spel2AP.upgrades,
        name = "Starter Vlad's Cape",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 5,
    },
    [Spel2AP.upgrades.Webgun] = {
        type = Spel2AP.upgrades,
        name = "Starter Webgun",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 0,
    },
    [Spel2AP.waddler_upgrades.Alien_Compass] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Alien Compass",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 5,
    },
    [Spel2AP.waddler_upgrades.Ankh] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Ankh",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 5,
    },
    [Spel2AP.waddler_upgrades.Arrow_of_Light] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Arrow of Light",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 5,
        TileX = 1,
    },
    [Spel2AP.waddler_upgrades.Camera] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Camera",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 4,
    },
    [Spel2AP.waddler_upgrades.Cape] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Cape",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 7,
    },
    [Spel2AP.waddler_upgrades.Climbing_Gloves] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Climbing Gloves",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 5,
    },
    [Spel2AP.waddler_upgrades.Clone_Gun] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Clone Gun",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 7,
    },
    [Spel2AP.waddler_upgrades.Compass] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Compass",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 9,
    },
    [Spel2AP.waddler_upgrades.Crown] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Crown",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 4,
    },
    [Spel2AP.waddler_upgrades.Eggplant] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Eggplant",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 4,
    },
    [Spel2AP.waddler_upgrades.Eggplant_Crown] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Eggplant Crown",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 5,
        TileX = 3,
    },
    [Spel2AP.waddler_upgrades.Elixir] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Elixir",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 6,
    },
    [Spel2AP.waddler_upgrades.Excalibur] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Excalibur",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 2,
        TileY = 10
    },
    [Spel2AP.waddler_upgrades.Four_Leaf_Clover] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Four-Leaf Clover",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 2,
    },
    [Spel2AP.waddler_upgrades.Freeze_Ray] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Freeze Ray",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 2,
    },
    [Spel2AP.waddler_upgrades.Hedjet] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Hedjet",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 3,
    },
    [Spel2AP.waddler_upgrades.Hoverpack] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Hoverpack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 6,
    },
    [Spel2AP.waddler_upgrades.Hou_Yis_Bow] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Hou Yi's Bow",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 5,
        TileX = 0,
    },
    [Spel2AP.waddler_upgrades.Jetpack] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Jetpack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 8,
    },
    [Spel2AP.waddler_upgrades.Kapala] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Kapala",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 2,
    },
    [Spel2AP.waddler_upgrades.Machete] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Machete",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 8,
    },
    [Spel2AP.waddler_upgrades.Mattock] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Mattock",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 6,
    },
    [Spel2AP.waddler_upgrades.Paste] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Paste",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 3,
    },
    [Spel2AP.waddler_upgrades.Pitchers_Mitt] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Pitcher's Mitt",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 6,
    },
    [Spel2AP.waddler_upgrades.Plasma_Cannon] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Plasma Cannon",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 0,
    },
    [Spel2AP.waddler_upgrades.Powerpack] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Powerpack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 4,
    },
    [Spel2AP.waddler_upgrades.Scepter] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Scepter",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 1,
    },
    [Spel2AP.waddler_upgrades.Shield] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Shield",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 1,
    },
    [Spel2AP.waddler_upgrades.Skeleton_Key] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Skeleton Key",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 8,
    },
    [Spel2AP.waddler_upgrades.Spectacles] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Spectacles",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 4,
    },
    [Spel2AP.waddler_upgrades.Spike_Shoes] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Spike Shoes",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 8,
    },
    [Spel2AP.waddler_upgrades.Spring_Shoes] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Spring Shoes",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 0,
        TileX = 7,
    },
    [Spel2AP.waddler_upgrades.Tablet_of_Destiny] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Tablet of Destiny",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 9,
    },
    [Spel2AP.waddler_upgrades.Telepack] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Telepack",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 9,
    },
    [Spel2AP.waddler_upgrades.Teleporter] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Teleporter",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 5,
    },
    [Spel2AP.waddler_upgrades.True_Crown] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler True Crown",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 3,
    },
    [Spel2AP.waddler_upgrades.Udjat_Eye] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Udjat Eye",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 1,
        TileX = 1,
    },
    [Spel2AP.waddler_upgrades.Ushabti] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Ushabti",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 3,
        TileX = 3,
    },
    [Spel2AP.waddler_upgrades.Vlads_Cape] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Vlad's Cape",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 4,
        TileX = 5,
    },
    [Spel2AP.waddler_upgrades.Webgun] = {
        type = Spel2AP.waddler_upgrades,
        name = "Waddler Webgun",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_ITEMS_0,
        TileY = 2,
        TileX = 0,
    },
    [Spel2AP.permanent_upgrades.Health] = {
        type = Spel2AP.permanent_upgrades,
        name = "Starting Health Upgrade",
        display = TEXTURE.DATA_TEXTURES_FX_SMALL_0,
        TileY = 7,
        TileX = 7,
    },
    [Spel2AP.permanent_upgrades.Bomb] = {
        type = Spel2AP.permanent_upgrades,
        name = "Bomb Upgrade",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 5,
        TileX = 0,
    },
    [Spel2AP.permanent_upgrades.Rope] = {
        type = Spel2AP.permanent_upgrades,
        name = "Rope Upgrade",
        display = TEXTURE.DATA_TEXTURES_CHAR_YELLOW_0,
        TileY = 12,
        TileX = 4,
    },
    [Spel2AP.permanent_upgrades.Cosmic_Ocean_Checkpoint] = {
        type = Spel2AP.permanent_upgrades,
        name = "Cosmic Ocean Checkpoint",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_BG_0,
        TileX = 1,
        TileY = 2
    },
    [Spel2AP.world_unlocks.Progressive_World] = {
        type = Spel2AP.world_unlocks,
        name = "Progress World Unlocked",
        display = TEXTURE.DATA_TEXTURES_FX_SMALL3_0,
        TileY = 6,
        TileX = 6,
    },
    [Spel2AP.world_unlocks.Jungle] = {
        type = Spel2AP.world_unlocks,
        name = "Jungle Unlocked",
        display = TEXTURE.DATA_TEXTURES_MENU_DEATHMATCH5_0,
        TileY = 0,
        TileX = 1,
    },
    [Spel2AP.world_unlocks.Volcana] = {
        type = Spel2AP.world_unlocks,
        name = "Volcana Unlocked",
        display = TEXTURE.DATA_TEXTURES_MENU_DEATHMATCH5_0,
        TileY = 0,
        TileX = 2,
    },
    [Spel2AP.world_unlocks.Olmecs_Lair] = {
        type = Spel2AP.world_unlocks,
        name = "Olmec's Lair Unlocked",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_MONS_BIG_0,
        TileY = 0,
        TileX = 1,
    },
    [Spel2AP.world_unlocks.Tide_Pool] = {
        type = Spel2AP.world_unlocks,
        name = "Tide Pool Unlocked",
        display = TEXTURE.DATA_TEXTURES_MENU_DEATHMATCH5_0,
        TileY = 0,
        TileX = 3,
    },
    [Spel2AP.world_unlocks.Temple] = {
        type = Spel2AP.world_unlocks,
        name = "Temple Unlocked",
        display = TEXTURE.DATA_TEXTURES_MENU_DEATHMATCH5_0,
        TileY = 1,
        TileX = 0,
    },
    [Spel2AP.world_unlocks.Ice_Caves] = {
        type = Spel2AP.world_unlocks,
        name = "Ice Caves Unlocked",
        display = TEXTURE.DATA_TEXTURES_MENU_DEATHMATCH5_0,
        TileY = 1,
        TileX = 1,
    },
    [Spel2AP.world_unlocks.Neo_Babylon] = {
        type = Spel2AP.world_unlocks,
        name = "Neo Babylon Unlocked",
        display = TEXTURE.DATA_TEXTURES_MENU_DEATHMATCH5_0,
        TileY = 1,
        TileX = 2,
    },
    [Spel2AP.world_unlocks.Sunken_City] = {
        type = Spel2AP.world_unlocks,
        name = "Sunken City Unlocked",
        display = TEXTURE.DATA_TEXTURES_MENU_DEATHMATCH5_0,
        TileY = 1,
        TileX = 3,
    },
    [Spel2AP.world_unlocks.Cosmic_Ocean] = {
        type = Spel2AP.world_unlocks,
        name = "Cosmic Ocean Unlocked",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 0,
        TileY = 0
    },
    [Spel2AP.shortcuts.Jungle] = {
        type = Spel2AP.shortcuts,
        name = "Jungle Shortcut",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 0,
        TileY = 0
    },
    [Spel2AP.shortcuts.Volcana] = {
        type = Spel2AP.shortcuts,
        name = "Volcana Shortcut",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 0,
        TileY = 0
    },
    [Spel2AP.shortcuts.Olmecs_Lair] = {
        type = Spel2AP.shortcuts,
        name = "Olmec's Lair Shortcut",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 0,
        TileY = 0
    },
    [Spel2AP.shortcuts.Tide_Pool] = {
        type = Spel2AP.shortcuts,
        name = "Tide Pool Shortcut",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 0,
        TileY = 0
    },
    [Spel2AP.shortcuts.Temple] = {
        type = Spel2AP.shortcuts,
        name = "Temple Shortcut",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 0,
        TileY = 0
    },
    [Spel2AP.shortcuts.Ice_Caves] = {
        type = Spel2AP.shortcuts,
        name = "Ice Caves Shortcut",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 0,
        TileY = 0
    },
    [Spel2AP.shortcuts.Neo_Babylon] = {
        type = Spel2AP.shortcuts,
        name = "Neo Babylon Shortcut",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 0,
        TileY = 0
    },
    [Spel2AP.shortcuts.Sunken_City] = {
        type = Spel2AP.shortcuts,
        name = "Sunken City Shortcut",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileX = 0,
        TileY = 0
    },
    [Spel2AP.traps.Poison] = {
        type = Spel2AP.traps,
        name = "Poison Trap",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 14,
        TileX = 3,
    },
    [Spel2AP.traps.Curse] = {
        type = Spel2AP.traps,
        name = "Curse Trap",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 15,
        TileX = 4,
    },
    [Spel2AP.traps.Ghost] = {
        type = Spel2AP.traps,
        name = "Ghost Trap",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_PEOPLE_0,
        TileY = 3,
        TileX = 3,
    },
    [Spel2AP.traps.Stun] = {
        type = Spel2AP.traps,
        name = "Stun Trap",
        display = TEXTURE.DATA_TEXTURES_CHAR_YELLOW_0,
        TileY = 13,
        TileX = 4,
    },
    [Spel2AP.traps.Loose_Bombs] = {
        type = Spel2AP.traps,
        name = "Loose Bombs Trap",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 6,
        TileX = 2,
    },
    [Spel2AP.traps.Blindness] = {
        type = Spel2AP.traps,
        name = "Blindness Trap",
        display = TEXTURE.DATA_TEXTURES_FX_SMALL3_0,
        TileY = 6,
        TileX = 0,
    },
    [Spel2AP.traps.Amnesia] = {
        type = Spel2AP.traps,
        name = "Amnesia Trap",
        display = TEXTURE.DATA_TEXTURES_FX_SMALL_0,
        TileY = 3,
        TileX = 3,
    },
    [Spel2AP.traps.Angry_Shopkeepers] = {
        type = Spel2AP.traps,
        name = "Angry Shopkeepers Trap",
        display = TEXTURE.DATA_TEXTURES_JOURNAL_ENTRY_PEOPLE_0,
        TileY = 2,
        TileX = 2,
    },
    [Spel2AP.traps.Punish_Ball] = {
        type = Spel2AP.traps,
        name = "Punish Ball Trap",
        display = TEXTURE.DATA_TEXTURES_ITEMS_0,
        TileY = 6,
        TileX = 11,
    }
}

AP_Goal = {
    EASY = 0,
    HARD = 1,
    CO = 2
}

ItemCode_to_Index = {
    [Spel2AP.upgrades.Ankh]             = 19, [Spel2AP.waddler_upgrades.Ankh]             = 19, [Spel2AP.locked_items.Ankh]             = 19,
    [Spel2AP.upgrades.Camera]           = 34, [Spel2AP.waddler_upgrades.Camera]           = 34, [Spel2AP.locked_items.Camera]           = 34,
    [Spel2AP.upgrades.Cape]             = 23, [Spel2AP.waddler_upgrades.Cape]             = 23, [Spel2AP.locked_items.Cape]             = 23,
    [Spel2AP.upgrades.Climbing_Gloves]  = 6,  [Spel2AP.waddler_upgrades.Climbing_Gloves]  = 6,  [Spel2AP.locked_items.Climbing_Gloves]  = 6,
    [Spel2AP.upgrades.Clone_Gun]        = 32, [Spel2AP.waddler_upgrades.Clone_Gun]        = 32, [Spel2AP.locked_items.Clone_Gun]        = 32,
    [Spel2AP.upgrades.Compass]          = 10, [Spel2AP.waddler_upgrades.Compass]          = 10, [Spel2AP.locked_items.Compass]          = 10,
    [Spel2AP.upgrades.Eggplant]         = 51, [Spel2AP.waddler_upgrades.Eggplant]         = 51, [Spel2AP.locked_items.Eggplant]         = 51,
    [Spel2AP.upgrades.Eggplant_Crown]   = 17, [Spel2AP.waddler_upgrades.Eggplant_Crown]   = 17, [Spel2AP.locked_items.Eggplant_Crown]   = 17,
    [Spel2AP.upgrades.Elixir]           = 53, [Spel2AP.waddler_upgrades.Elixir]           = 53, [Spel2AP.locked_items.Elixir]           = 53,
    [Spel2AP.upgrades.Four_Leaf_Clover] = 54, [Spel2AP.waddler_upgrades.Four_Leaf_Clover] = 54, [Spel2AP.locked_items.Four_Leaf_Clover] = 54,
    [Spel2AP.upgrades.Freeze_Ray]       = 31, [Spel2AP.waddler_upgrades.Freeze_Ray]       = 31, [Spel2AP.locked_items.Freeze_Ray]       = 31,
    [Spel2AP.upgrades.Hoverpack]        = 27, [Spel2AP.waddler_upgrades.Hoverpack]        = 27, [Spel2AP.locked_items.Hoverpack]        = 27,
    [Spel2AP.upgrades.Jetpack]          = 25, [Spel2AP.waddler_upgrades.Jetpack]          = 25, [Spel2AP.locked_items.Jetpack]          = 25,
    [Spel2AP.upgrades.Kapala]           = 14, [Spel2AP.waddler_upgrades.Kapala]           = 14, [Spel2AP.locked_items.Kapala]           = 14,
    [Spel2AP.upgrades.Machete]          = 38, [Spel2AP.waddler_upgrades.Machete]          = 38, [Spel2AP.locked_items.Machete]          = 38,
    [Spel2AP.upgrades.Mattock]          = 36, [Spel2AP.waddler_upgrades.Mattock]          = 36, [Spel2AP.locked_items.Mattock]          = 36,
    [Spel2AP.upgrades.Paste]            = 4,  [Spel2AP.waddler_upgrades.Paste]            = 4,  [Spel2AP.locked_items.Paste]            = 4,
    [Spel2AP.upgrades.Pitchers_Mitt]    = 7,  [Spel2AP.waddler_upgrades.Pitchers_Mitt]    = 7,  [Spel2AP.locked_items.Pitchers_Mitt]    = 7,
    [Spel2AP.upgrades.Plasma_Cannon]    = 41, [Spel2AP.waddler_upgrades.Plasma_Cannon]    = 41, [Spel2AP.locked_items.Plasma_Cannon]    = 41,
    [Spel2AP.upgrades.Powerpack]        = 28, [Spel2AP.waddler_upgrades.Powerpack]        = 28, [Spel2AP.locked_items.Powerpack]        = 28,
    [Spel2AP.upgrades.Shield]           = 46, [Spel2AP.waddler_upgrades.Shield]           = 46, [Spel2AP.locked_items.Shield]           = 46,
    [Spel2AP.upgrades.Skeleton_Key]     = 21, [Spel2AP.waddler_upgrades.Skeleton_Key]     = 21, [Spel2AP.locked_items.Skeleton_Key]     = 21,
    [Spel2AP.upgrades.Spectacles]       = 5,  [Spel2AP.waddler_upgrades.Spectacles]       = 5,  [Spel2AP.locked_items.Spectacles]       = 5,
    [Spel2AP.upgrades.Spike_Shoes]      = 9,  [Spel2AP.waddler_upgrades.Spike_Shoes]      = 9,  [Spel2AP.locked_items.Spike_Shoes]      = 9,
    [Spel2AP.upgrades.Spring_Shoes]     = 8,  [Spel2AP.waddler_upgrades.Spring_Shoes]     = 8,  [Spel2AP.locked_items.Spring_Shoes]     = 8,
    [Spel2AP.upgrades.Telepack]         = 26, [Spel2AP.waddler_upgrades.Telepack]         = 26, [Spel2AP.locked_items.Telepack]         = 26,
    [Spel2AP.upgrades.Teleporter]       = 35, [Spel2AP.waddler_upgrades.Teleporter]       = 35, [Spel2AP.locked_items.Teleporter]       = 35,
    [Spel2AP.upgrades.True_Crown]       = 18, [Spel2AP.waddler_upgrades.True_Crown]       = 18, [Spel2AP.locked_items.True_Crown]       = 18,
    [Spel2AP.upgrades.Vlads_Cape]       = 24, [Spel2AP.waddler_upgrades.Vlads_Cape]       = 24, [Spel2AP.locked_items.Vlads_Cape]       = 24,
    [Spel2AP.upgrades.Webgun]           = 29, [Spel2AP.waddler_upgrades.Webgun]           = 29, [Spel2AP.locked_items.Webgun]           = 29,

    [Spel2AP.waddler_upgrades.Alien_Compass]     = 11, [Spel2AP.locked_items.Alien_Compass]     = 11,
    [Spel2AP.waddler_upgrades.Arrow_of_Light]    = 44, [Spel2AP.locked_items.Arrow_of_Light]    = 44,
    [Spel2AP.waddler_upgrades.Crown]             = 16, [Spel2AP.locked_items.Crown]             = 16,
    [Spel2AP.waddler_upgrades.Excalibur]         = 39, [Spel2AP.locked_items.Excalibur]         = 39,
    [Spel2AP.waddler_upgrades.Hedjet]            = 15, [Spel2AP.locked_items.Hedjet]            = 15,
    [Spel2AP.waddler_upgrades.Hou_Yis_Bow]       = 43, [Spel2AP.locked_items.Hou_Yis_Bow]       = 43,
    [Spel2AP.waddler_upgrades.Scepter]           = 42, [Spel2AP.locked_items.Scepter]           = 42,
    [Spel2AP.waddler_upgrades.Tablet_of_Destiny] = 20, [Spel2AP.locked_items.Tablet_of_Destiny] = 20,
    [Spel2AP.waddler_upgrades.Udjat_Eye]         = 13, [Spel2AP.locked_items.Udjat_Eye]         = 13,
    [Spel2AP.waddler_upgrades.Ushabti]           = 50, [Spel2AP.locked_items.Ushabti]           = 50,
}

Journal_to_ItemEnt = {
    [4]  = { type = ENT_TYPE.ITEM_PICKUP_PASTE,                     lock = Spel2AP.locked_items.Paste,              powerup = ENT_TYPE.ITEM_POWERUP_PASTE },
    [5]  = { type = ENT_TYPE.ITEM_PICKUP_SPECTACLES,                lock = Spel2AP.locked_items.Spectacles,         powerup = ENT_TYPE.ITEM_POWERUP_SPECTACLES },
    [6]  = { type = ENT_TYPE.ITEM_PICKUP_CLIMBINGGLOVES,            lock = Spel2AP.locked_items.Climbing_Gloves,    powerup = ENT_TYPE.ITEM_POWERUP_CLIMBING_GLOVES },
    [7]  = { type = ENT_TYPE.ITEM_PICKUP_PITCHERSMITT,              lock = Spel2AP.locked_items.Pitchers_Mitt,      powerup = ENT_TYPE.ITEM_POWERUP_PITCHERSMITT },
    [8]  = { type = ENT_TYPE.ITEM_PICKUP_SPRINGSHOES,               lock = Spel2AP.locked_items.Spring_Shoes,       powerup = ENT_TYPE.ITEM_POWERUP_SPRING_SHOES },
    [9]  = { type = ENT_TYPE.ITEM_PICKUP_SPIKESHOES,                lock = Spel2AP.locked_items.Spike_Shoes,        powerup = ENT_TYPE.ITEM_POWERUP_SPIKE_SHOES },
    [10] = { type = ENT_TYPE.ITEM_PICKUP_COMPASS,                   lock = Spel2AP.locked_items.Compass,            powerup = ENT_TYPE.ITEM_POWERUP_COMPASS },
    [11] = { type = ENT_TYPE.ITEM_PICKUP_SPECIALCOMPASS,            lock = Spel2AP.locked_items.Alien_Compass,      powerup = ENT_TYPE.ITEM_POWERUP_SPECIALCOMPASS },
    [13] = { type = ENT_TYPE.ITEM_PICKUP_UDJATEYE,                  lock = Spel2AP.locked_items.Udjat_Eye,          powerup = ENT_TYPE.ITEM_POWERUP_UDJATEYE },
    [14] = { type = ENT_TYPE.ITEM_PICKUP_KAPALA,                    lock = Spel2AP.locked_items.Kapala,             powerup = ENT_TYPE.ITEM_POWERUP_KAPALA },
    [15] = { type = ENT_TYPE.ITEM_PICKUP_HEDJET,                    lock = Spel2AP.locked_items.Hedjet,             powerup = ENT_TYPE.ITEM_POWERUP_HEDJET },
    [16] = { type = ENT_TYPE.ITEM_PICKUP_CROWN,                     lock = Spel2AP.locked_items.Crown,              powerup = ENT_TYPE.ITEM_POWERUP_CROWN },
    [17] = { type = ENT_TYPE.ITEM_PICKUP_EGGPLANTCROWN,             lock = Spel2AP.locked_items.Eggplant_Crown,     powerup = ENT_TYPE.ITEM_POWERUP_EGGPLANTCROWN },
    [18] = { type = ENT_TYPE.ITEM_PICKUP_TRUECROWN,                 lock = Spel2AP.locked_items.True_Crown,         powerup = ENT_TYPE.ITEM_POWERUP_TRUECROWN },
    [19] = { type = ENT_TYPE.ITEM_PICKUP_ANKH,                      lock = Spel2AP.locked_items.Ankh,               powerup = ENT_TYPE.ITEM_POWERUP_ANKH },
    [20] = { type = ENT_TYPE.ITEM_PICKUP_TABLETOFDESTINY,           lock = Spel2AP.locked_items.Tablet_of_Destiny,  powerup = ENT_TYPE.ITEM_POWERUP_TABLETOFDESTINY },
    [21] = { type = ENT_TYPE.ITEM_PICKUP_SKELETON_KEY,              lock = Spel2AP.locked_items.Skeleton_Key,       powerup = ENT_TYPE.ITEM_POWERUP_SKELETON_KEY },
    [23] = { type = ENT_TYPE.ITEM_CAPE,                             lock = Spel2AP.locked_items.Cape },
    [24] = { type = ENT_TYPE.ITEM_VLADS_CAPE,                       lock = Spel2AP.locked_items.Vlads_Cape },
    [25] = { type = ENT_TYPE.ITEM_JETPACK,                          lock = Spel2AP.locked_items.Jetpack },
    [26] = { type = ENT_TYPE.ITEM_TELEPORTER_BACKPACK,              lock = Spel2AP.locked_items.Telepack },
    [27] = { type = ENT_TYPE.ITEM_HOVERPACK,                        lock = Spel2AP.locked_items.Hoverpack },
    [28] = { type = ENT_TYPE.ITEM_POWERPACK,                        lock = Spel2AP.locked_items.Powerpack },
    [29] = { type = ENT_TYPE.ITEM_WEBGUN,                           lock = Spel2AP.locked_items.Webgun },
    [31] = { type = ENT_TYPE.ITEM_FREEZERAY,                        lock = Spel2AP.locked_items.Freeze_Ray },
    [32] = { type = ENT_TYPE.ITEM_CLONEGUN,                         lock = Spel2AP.locked_items.Clone_Gun },
    [34] = { type = ENT_TYPE.ITEM_CAMERA,                           lock = Spel2AP.locked_items.Camera },
    [35] = { type = ENT_TYPE.ITEM_TELEPORTER,                       lock = Spel2AP.locked_items.Teleporter },
    [36] = { type = ENT_TYPE.ITEM_MATTOCK,                          lock = Spel2AP.locked_items.Mattock },
    [38] = { type = ENT_TYPE.ITEM_MACHETE,                          lock = Spel2AP.locked_items.Machete },
    [39] = { type = ENT_TYPE.ITEM_EXCALIBUR,                        lock = Spel2AP.locked_items.Excalibur },
    [41] = { type = ENT_TYPE.ITEM_PLASMACANNON,                     lock = Spel2AP.locked_items.Plasma_Cannon },
    [42] = { type = ENT_TYPE.ITEM_SCEPTER,                          lock = Spel2AP.locked_items.Scepter },
    [43] = { type = ENT_TYPE.ITEM_HOUYIBOW,                         lock = Spel2AP.locked_items.Hou_Yis_Bow },
    [44] = { type = ENT_TYPE.ITEM_LIGHT_ARROW,                      lock = Spel2AP.locked_items.Arrow_of_Light },
    [46] = { type = ENT_TYPE.ITEM_METAL_SHIELD,                     lock = Spel2AP.locked_items.Shield },
    [50] = { type = ENT_TYPE.ITEM_USHABTI,                          lock = Spel2AP.locked_items.Ushabti },
    [51] = { type = ENT_TYPE.ITEM_EGGPLANT,                         lock = Spel2AP.locked_items.Eggplant },
    [53] = { type = ENT_TYPE.ITEM_PICKUP_ELIXIR,                    lock = Spel2AP.locked_items.Elixir },
    [54] = { type = ENT_TYPE.ITEM_PICKUP_CLOVER,                    lock = Spel2AP.locked_items.Four_Leaf_Clover },
    [123] = { type = ENT_TYPE.ITEM_PURCHASABLE_CAPE,                lock = Spel2AP.locked_items.Cape },
    [126] = { type = ENT_TYPE.ITEM_PURCHASABLE_TELEPORTER_BACKPACK, lock = Spel2AP.locked_items.Telepack },
    [127] = { type = ENT_TYPE.ITEM_PURCHASABLE_HOVERPACK,           lock = Spel2AP.locked_items.Hoverpack },
    [128] = { type = ENT_TYPE.ITEM_PURCHASABLE_POWERPACK,           lock = Spel2AP.locked_items.Powerpack },
    [125] = { type = ENT_TYPE.ITEM_PURCHASABLE_JETPACK,             lock = Spel2AP.locked_items.Jetpack },
}

default_dice_prizes = {
    ENT_TYPE.ITEM_PICKUP_BOMBBAG,
    ENT_TYPE.ITEM_PICKUP_BOMBBOX,
    ENT_TYPE.ITEM_PICKUP_ROPEPILE,
    ENT_TYPE.ITEM_PICKUP_COMPASS,
    ENT_TYPE.ITEM_PICKUP_PASTE,
    ENT_TYPE.ITEM_PICKUP_PARACHUTE,
    ENT_TYPE.ITEM_PURCHASABLE_CAPE,
    ENT_TYPE.ITEM_PICKUP_SPECTACLES,
    ENT_TYPE.ITEM_PICKUP_CLIMBINGGLOVES,
    ENT_TYPE.ITEM_PICKUP_PITCHERSMITT,
    ENT_TYPE.ITEM_PICKUP_SPIKESHOES,
    ENT_TYPE.ITEM_PICKUP_SPRINGSHOES,
    ENT_TYPE.ITEM_MACHETE,
    ENT_TYPE.ITEM_BOOMERANG,
    ENT_TYPE.ITEM_CROSSBOW,
    ENT_TYPE.ITEM_SHOTGUN,
    ENT_TYPE.ITEM_FREEZERAY,
    ENT_TYPE.ITEM_WEBGUN,
    ENT_TYPE.ITEM_CAMERA,
    ENT_TYPE.ITEM_MATTOCK,
    ENT_TYPE.ITEM_PURCHASABLE_JETPACK,
    ENT_TYPE.ITEM_PURCHASABLE_HOVERPACK,
    ENT_TYPE.ITEM_TELEPORTER,
    ENT_TYPE.ITEM_PURCHASABLE_TELEPORTER_BACKPACK,
    ENT_TYPE.ITEM_PURCHASABLE_POWERPACK
}

obnoxious_journal_entries = become_lookup_table
({
    Spel2AP.locations.bestiary.Magmar,
    Spel2AP.locations.bestiary.Lavamander,
    Spel2AP.locations.bestiary.Mech_Rider,
    Spel2AP.locations.bestiary.Scorpion,
    Spel2AP.locations.item.True_Crown,
})

hard_journal_entries = become_lookup_table
({
    Spel2AP.locations.place.Tiamats_Throne,
    Spel2AP.locations.place.Sunken_City,
    Spel2AP.locations.place.Eggplant_World,
    Spel2AP.locations.place.HunDunsHideaway,
    Spel2AP.locations.people.Dirk_Yamaoka,
    Spel2AP.locations.people.Guy_Spelunky,
    Spel2AP.locations.people.Eggplant_King,
    Spel2AP.locations.bestiary.Tiamat,
    Spel2AP.locations.bestiary.Tadpole,
    Spel2AP.locations.bestiary.Frog,
    Spel2AP.locations.bestiary.Fire_Frog,
    Spel2AP.locations.bestiary.Goliath_Frog,
    Spel2AP.locations.bestiary.Grub,
    Spel2AP.locations.bestiary.Giant_Fly,
    Spel2AP.locations.bestiary.Hundun,
    Spel2AP.locations.bestiary.Eggplant_Minister,
    Spel2AP.locations.bestiary.Eggplup,
    Spel2AP.locations.trap.Frog_Trap,
    Spel2AP.locations.trap.Sticky_Trap,
    Spel2AP.locations.trap.Bone_Drop,
    Spel2AP.locations.trap.Egg_Sac,
})

co_journal_entries = become_lookup_table
({
    Spel2AP.locations.place.Cosmic_Ocean,
    Spel2AP.locations.people.Classic_Guy,
    Spel2AP.locations.bestiary.Celestial_Jelly,
})

unrestricted_items = become_lookup_table
({
    ENT_TYPE.ITEM_PICKUP_ROPEPILE,
    ENT_TYPE.ITEM_PICKUP_BOMBBAG,
    ENT_TYPE.ITEM_PICKUP_BOMBBOX,
    ENT_TYPE.ITEM_PICKUP_PARACHUTE,
    ENT_TYPE.ITEM_SHOTGUN,
    ENT_TYPE.ITEM_CROSSBOW,
    ENT_TYPE.ITEM_BOOMERANG,
    ENT_TYPE.ITEM_PICKUP_ROYALJELLY,
    ENT_TYPE.ITEM_WOODEN_SHIELD,
})