name: Build release zips (manual test)

on:
  push:
    branches:
      - new_apworld

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1️⃣ Create spelunky2.apworld from .spelunky2 contents
      - name: Prepare spelunky2.apworld
        run: |
          mkdir spelunky2
          cp -r .spelunky2/* spelunky2/
          zip -r spelunky2.apworld spelunky2

      # 2️⃣ Create Spelunky2-Client.zip from everything else
      - name: Prepare Spelunky2-Client.zip
        run: |
          mkdir client
          shopt -s extglob
          cp -r !(.spelunky2|.git|.github|client) client/
          cd client
          zip -r ../Spelunky2-Client.zip .

      # 3️⃣ Upload spelunky2.apworld as its own artifact
      - name: Upload spelunky2.apworld
        uses: actions/upload-artifact@v4
        with:
          name: spelunky2.apworld
          path: spelunky2.apworld

      # 4️⃣ Upload Spelunky2-Client.zip as its own artifact
      - name: Upload Spelunky2-Client.zip
        uses: actions/upload-artifact@v4
        with:
          name: Spelunky2-Client.zip
          path: Spelunky2-Client.zip
