name: Build and attach release zips

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #Create spelunky2.apworld
      - name: Prepare spelunky2.apworld
        run: |
          mkdir spelunky2
          cp -r .spelunky2/* spelunky2/
          zip -r spelunky2.apworld spelunky2

      #Create Spelunky2-Client.zip
      - name: Prepare Spelunky2-Client.zip
        run: |
          mkdir client
          shopt -s extglob
          cp -r !(.spelunky2|.git|.github|client) client/
          cd client
          zip -r ../Spelunky2-Client.zip .

      # Attach spelunky2.apworld to the release
      - name: Upload spelunky2.apworld to release
        uses: softprops/action-gh-release@v1
        with:
          files: spelunky2.apworld
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Attach Spelunky2-Client.zip to the release
      - name: Upload Spelunky2-Client.zip to release
        uses: softprops/action-gh-release@v1
        with:
          files: Spelunky2-Client.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
