name: Build and attach release zips

on:
  release:
    types: [published, edited]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Pre-clean: remove repo-only files/folders we never want in zips
      - name: Pre-clean workspace
        run: |
          rm -rf .git .github README.md

      # Step 1: Prepare APworld
      - name: Prepare APworld
        run: |
          mv .spelunky2 spelunky2
          zip -r spelunky2.apworld spelunky2
          rm -rf spelunky2

      # Step 2: Upload APworld to release
      - name: Upload APworld to release
        uses: softprops/action-gh-release@v1
        with:
          files: spelunky2.apworld
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Remove APworld file so it can't leak into APClient
      - name: Cleanup APworld artifact
        run: |
          rm -f spelunky2.apworld

      # Step 4: Prepare APClient
      - name: Prepare APClient
        run: |
          zip -r Spelunky2-Archipelago.zip .

      # Step 5: Upload APClient to release
      - name: Upload APClient to release
        uses: softprops/action-gh-release@v1
        with:
          files: Spelunky2-Archipelago.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
